# VacationPy
----

#### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [74]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [75]:
# File to Load (Remember to Change These)
file_to_load = "../output_data/cities.csv"

cities_df = pd.read_csv(file_to_load)

cities_df = cities_df[['City','Lat','Lng','Max Temp','Humidity','Cloudiness','Wind Speed','Country','Date']]
cities_df

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,Talcahuano,-36.72,-73.12,48.200,87,0,2.10,CL,1597627040
1,Bathsheba,13.22,-59.52,80.600,88,75,9.30,BB,1597627040
2,Kavaratti,10.57,72.64,81.734,80,96,6.67,IN,1597627041
3,La Plata,-34.92,-57.95,62.006,30,0,1.79,AR,1597626772
4,Richards Bay,-28.78,32.04,59.612,61,10,3.36,ZA,1597627041
...,...,...,...,...,...,...,...,...,...
577,Lata,40.16,-8.33,64.004,94,93,1.00,PT,1597627219
578,Kenai,60.55,-151.26,77.000,29,1,4.10,US,1597627220
579,Buraidah,26.33,43.98,84.200,28,99,2.60,SA,1597627220
580,Sarny,51.34,26.60,59.000,68,0,1.44,UA,1597627220
581,Tsogni,-2.79,10.10,72.356,89,100,2.77,GA,1597627221

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [76]:
# Configure gmaps
gmaps.configure(api_key=g_key)

In [77]:
# Store latitude and longitude in locations
locations = cities_df[["Lat", "Lng"]]
weight = cities_df["Humidity"].astype(float)

# Plot Heatmap
#fig = gmaps.figure()
fig = gmaps.figure(center=(46.0, -5.0), zoom_level=2)

#Create heat layer
heat_layer = gmaps.heatmap_layer(locations, weights=weight, 
                                dissipating=False, max_intensity=100,
                                point_radius=3)

#Add layer
fig.add_layer(heat_layer)

#Display figure
fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [79]:
# Narrow down the DataFrame to find your ideal weather condition. For example:
# A max temperature lower than 80 degrees but higher than 70.
# Wind speed less than 10 mph.
# Zero cloudiness.
# Drop any rows that don't contain all three conditions. You want to be sure the weather is ideal.
# Note: Feel free to adjust to your specifications but be sure to limit the number of rows 
# returned by your API requests to a reasonable number.


hotel_df = pd.DataFrame(cities_df.loc[(cities_df["Max Temp"] < 80) & 
                         (cities_df["Max Temp"] > 70) & 
                         (cities_df["Wind Speed"] < 10) &
                         (cities_df["Cloudiness"] == 0)])
hotel_df

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
9,Atuona,-9.80,-139.03,78.278,76,0,7.12,PF,1597627042
42,Bengkulu,-3.80,102.27,79.556,74,0,0.98,ID,1597626833
68,Alice Springs,-23.70,133.88,78.800,19,0,7.20,AU,1597626870
92,Palafrugell,41.92,3.16,71.996,53,0,2.26,ES,1597627066
142,Erzin,36.96,36.20,75.992,86,0,0.60,TR,1597627083
243,Brenes,37.55,-5.87,71.996,68,0,2.10,ES,1597627114
274,Kiryat Gat,31.61,34.76,73.994,58,0,0.89,IL,1597626901
308,Merauke,-8.47,140.33,79.664,66,0,4.19,ID,1597627133
311,Jacareacanga,-6.22,-57.75,79.376,38,0,0.44,BR,1597627064
313,Kashgar,39.45,75.98,75.200,38,0,2.00,CN,1597627134
325,Tūkrah,32.53,20.58,77.360,85,0,4.03,LY,1597627138
355,Mount Isa,-20.73,139.50,75.200,18,0,4.60,AU,1597627147
357,San Quintín,30.48,-115.95,77.612,63,0,4.45,MX,1597627147
365,Methóni,36.82,21.70,78.998,88,0,1.99,GR,1597627149
390,Benghazi,32.12,20.07,78.836,81,0,5.09,LY,1597627158
397,Faanui,-16.48,-151.75,78.098,68,0,4.81,PF,1597627118
410,Kasongo-Lunda,-6.47,16.82,72.446,74,0,1.16,CD,1597627163
422,Aksu,41.12,80.26,75.560,25,0,2.34,CN,1597627168
488,Chu,43.60,73.76,72.752,41,0,1.25,KZ,1597627188
504,Banamba,13.55,-7.45,76.640,84,0,2.93,ML,1597627193
520,Fare,-16.70,-151.02,78.836,69,0,4.50,PF,1597627198

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [80]:
hotel_df['Hotel Name'] = ""
hotel_df

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,Hotel Name
9,Atuona,-9.80,-139.03,78.278,76,0,7.12,PF,1597627042,
42,Bengkulu,-3.80,102.27,79.556,74,0,0.98,ID,1597626833,
68,Alice Springs,-23.70,133.88,78.800,19,0,7.20,AU,1597626870,
92,Palafrugell,41.92,3.16,71.996,53,0,2.26,ES,1597627066,
142,Erzin,36.96,36.20,75.992,86,0,0.60,TR,1597627083,
243,Brenes,37.55,-5.87,71.996,68,0,2.10,ES,1597627114,
274,Kiryat Gat,31.61,34.76,73.994,58,0,0.89,IL,1597626901,
308,Merauke,-8.47,140.33,79.664,66,0,4.19,ID,1597627133,
311,Jacareacanga,-6.22,-57.75,79.376,38,0,0.44,BR,1597627064,
313,Kashgar,39.45,75.98,75.200,38,0,2.00,CN,1597627134,
325,Tūkrah,32.53,20.58,77.360,85,0,4.03,LY,1597627138,
355,Mount Isa,-20.73,139.50,75.200,18,0,4.60,AU,1597627147,
357,San Quintín,30.48,-115.95,77.612,63,0,4.45,MX,1597627147,
365,Methóni,36.82,21.70,78.998,88,0,1.99,GR,1597627149,
390,Benghazi,32.12,20.07,78.836,81,0,5.09,LY,1597627158,
397,Faanui,-16.48,-151.75,78.098,68,0,4.81,PF,1597627118,
410,Kasongo-Lunda,-6.47,16.82,72.446,74,0,1.16,CD,1597627163,
422,Aksu,41.12,80.26,75.560,25,0,2.34,CN,1597627168,
488,Chu,43.60,73.76,72.752,41,0,1.25,KZ,1597627188,
504,Banamba,13.55,-7.45,76.640,84,0,2.93,ML,1597627193,
520,Fare,-16.70,-151.02,78.836,69,0,4.50,PF,1597627198,

In [83]:
# Using Google Places API to find the first hotel for each city located within 5000 meters of your coordinates.

base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

#https://maps.googleapis.com/maps/api/place/nearbysearch/
#json?location=-33.8670522,151.1957362
#&radius=5000
#&type=lodging
#&key=YOUR_API_KEY

# use iterrows to iterate through pandas dataframe
for index, row in hotel_df.iterrows():
    
    strL = row["Lat"]
    strL2 = row["Lng"]
    
    params = {
    "location": f"{strL},{strL2}",  
    "type": "lodging",
    "radius" : 5000,
    "key": g_key,
    }

    # assemble url and make API request
    currCity = row["City"]
    print(f"Retrieving Results for city : {currCity}")
    response = requests.get(base_url, params=params).json()
    
    # extract results
    results = response['results']
    
    try:
        print(f"Closest hotel is {results[0]['name']}.")
        
        hotel_df.loc[index, 'Hotel Name'] = results[0]['name']
        
    except (KeyError, IndexError):
        print("Missing field/result... skipping.")
        hotel_df.loc[index, 'Hotel Name'] = 'None found'

        
    print("------------")

Retrieving Results for city : Atuona
Closest hotel is Villa Enata.
------------
Retrieving Results for city : Bengkulu
Closest hotel is Grage Hotel Bengkulu.
------------
Retrieving Results for city : Alice Springs
Closest hotel is Desert Palms Alice Springs.
------------
Retrieving Results for city : Palafrugell
Closest hotel is Hotel Garbi.
------------
Retrieving Results for city : Erzin
Closest hotel is Artemis Otel.
------------
Retrieving Results for city : Brenes
Closest hotel is Hotel El Juncal.
------------
Retrieving Results for city : Kiryat Gat
Closest hotel is רגע בנחת.
------------
Retrieving Results for city : Merauke
Missing field/result... skipping.
------------
Retrieving Results for city : Jacareacanga
Closest hotel is Casa do Ian😎.
------------
Retrieving Results for city : Kashgar
Closest hotel is 帕米尔青年旅舍.
------------
Retrieving Results for city : Tūkrah
Closest hotel is استراحة لاقروتا.
------------
Retrieving Results for city : Mount Isa
Closest hotel is ibis Styles Mt Isa Verona.
------------
Retrieving Results for city : San Quintín
Closest hotel is Old Mill Hotel.
------------
Retrieving Results for city : Methóni
Closest hotel is Methoni Beach Hotel.
------------
Retrieving Results for city : Benghazi
Closest hotel is Tibesti Hotel.
------------
Retrieving Results for city : Faanui
Closest hotel is Bora-Bora Pearl Beach Resort & Spa.
------------
Retrieving Results for city : Kasongo-Lunda
Missing field/result... skipping.
------------
Retrieving Results for city : Aksu
Closest hotel is Pudong Holiday Hotel.
------------
Retrieving Results for city : Chu
Closest hotel is Shyngyzkhan.
------------
Retrieving Results for city : Banamba
Closest hotel is Kassela de Banamba.
------------
Retrieving Results for city : Fare
Closest hotel is Maitai Lapita Village Huahine.
------------

In [84]:
hotel_df

,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,Hotel Name
9,Atuona,-9.80,-139.03,78.278,76,0,7.12,PF,1597627042,Villa Enata
42,Bengkulu,-3.80,102.27,79.556,74,0,0.98,ID,1597626833,Grage Hotel Bengkulu
68,Alice Springs,-23.70,133.88,78.800,19,0,7.20,AU,1597626870,Desert Palms Alice Springs
92,Palafrugell,41.92,3.16,71.996,53,0,2.26,ES,1597627066,Hotel Garbi
142,Erzin,36.96,36.20,75.992,86,0,0.60,TR,1597627083,Artemis Otel
243,Brenes,37.55,-5.87,71.996,68,0,2.10,ES,1597627114,Hotel El Juncal
274,Kiryat Gat,31.61,34.76,73.994,58,0,0.89,IL,1597626901,רגע בנחת
308,Merauke,-8.47,140.33,79.664,66,0,4.19,ID,1597627133,None found
311,Jacareacanga,-6.22,-57.75,79.376,38,0,0.44,BR,1597627064,Casa do Ian😎
313,Kashgar,39.45,75.98,75.200,38,0,2.00,CN,1597627134,帕米尔青年旅舍
325,Tūkrah,32.53,20.58,77.360,85,0,4.03,LY,1597627138,استراحة لاقروتا
355,Mount Isa,-20.73,139.50,75.200,18,0,4.60,AU,1597627147,ibis Styles Mt Isa Verona
357,San Quintín,30.48,-115.95,77.612,63,0,4.45,MX,1597627147,Old Mill Hotel
365,Methóni,36.82,21.70,78.998,88,0,1.99,GR,1597627149,Methoni Beach Hotel
390,Benghazi,32.12,20.07,78.836,81,0,5.09,LY,1597627158,Tibesti Hotel
397,Faanui,-16.48,-151.75,78.098,68,0,4.81,PF,1597627118,Bora-Bora Pearl Beach Resort & Spa
410,Kasongo-Lunda,-6.47,16.82,72.446,74,0,1.16,CD,1597627163,None found
422,Aksu,41.12,80.26,75.560,25,0,2.34,CN,1597627168,Pudong Holiday Hotel
488,Chu,43.60,73.76,72.752,41,0,1.25,KZ,1597627188,Shyngyzkhan
504,Banamba,13.55,-7.45,76.640,84,0,2.93,ML,1597627193,Kassela de Banamba
520,Fare,-16.70,-151.02,78.836,69,0,4.50,PF,1597627198,Maitai Lapita Village Huahine

In [86]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [90]:
# Plot the hotels on top of the humidity heatmap with each pin containing the Hotel Name, City, and Country.
# Add marker layer ontop of heat map
# Display figure

markers = gmaps.marker_layer(locations, info_box_content = hotel_info)

# Add the layer to the map
fig.add_layer(markers)

# Display Map
fig

Figure(layout=FigureLayout(height='420px'))